apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-pod
  namespace: default
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: default
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: writer-pod
  namespace: default
subjects:
  - kind: ServiceAccount
    name: writer
    namespace: default
roleRef:
  kind: Role
  name: writer
  apiGroup: rbac.authorization.k8s.io

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-pod
  namespace: default
subjects:
  - kind: ServiceAccount
    name: reader
    namespace: default
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
